### PR TITLE
Authenticate requests to Gerrit hook via HTTP basic auth

### PR DESCRIPTION
**Pull request by ccascone**
User and password can be set via Firebase functions config

### CODE REVIEW

**Comment by ccascone** [comment]
Do not merge until we also implement support in the Gerrit hook (ping @zdw)

**Comment by zdw** [comment]
Merging #119 should allow this to be merged

**Comment by zdw** [comment]
This needs a manual rebase as it doesn't apply cleanly to current master

**Comment by ccascone** [comment]
@zdw @teone I need at least one approval to merge this. Can you please review?

**Comment by zdw** [comment]
Updating the gerrit scripts now, will approve after

**Comment by zdw** [comment]
Gerrit hooks are updated, feel free to merge.

**Pull request merged**
