### PR TITLE
Adding firebase tool to circleci Docker image

### PR DESCRIPTION
**Pull request by teone**
**Describe the PR**
Adding `firebase` to the Docker image used in the test so that we can a `firebase:emulator` in there

Fixes #

### CODE REVIEW

**Review by hwchiu — APPROVED** [review]

**Comment by ccascone** [comment]
We already install firebase-tools as part of the circleci steps:
https://github.com/OpenNetworkingFoundation/cla-manager/blob/master/.circleci/config.yml#L102

If adding it to the docker image, we should probably remove related steps in config.yml, and make sure we call the globally installed `firebase` command everywhere.

**Comment by teone** [comment]
The reason I was installing it in docker is that we'll need in the tests too in order to test the firestore rules, but I'm also fine to add this in the `.circleci/config.yml`:
```
       # install the new dependencies for all the packages
+      - run:
+          name: Install Firebase Tools
+          command: npm install --prefix=./firebase-emulator firebase-tools
       - run: npm install
       - run: npm --prefix ./functions install
       - run: npm --prefix ./client install
       - run: npm --prefix ./common install
       # run the tests
-      - run: firebase emulators:exec --only firestore 'npm test'
+      - run: ./firebase-emulator/node_modules/.bin/firebase emulators:exec --only firestore 'npm test'
```
which approach do you prefer?

**Comment by ccascone** [comment]
Sorry, I never saw your reply until now. My preference would be to keep using firebase-tools as installed by functions/package.json (see comment [here](https://github.com/OpenNetworkingFoundation/cla-manager/pull/193#discussion_r514591980)), but I will not make a case for it.

**Comment by teone** [comment]
@ccascone makes sense, I don't have strong opinion so I'll leave it as it is now.

**Pull request closed without merging**
